// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceGenius.API.Data;

#nullable disable

namespace PriceGenius.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508174008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceGenius.API.Models.AgentDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AppliedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SuggestedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("WasOverridden")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("AgentDecisions");
                });

            modelBuilder.Entity("PriceGenius.API.Models.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 115m,
                            ProductId = 1,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 125m,
                            ProductId = 1,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 110m,
                            ProductId = 1,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 4,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 340m,
                            ProductId = 2,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 360m,
                            ProductId = 2,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 6,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 330m,
                            ProductId = 2,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 7,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 175m,
                            ProductId = 3,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 8,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 190m,
                            ProductId = 3,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 9,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 170m,
                            ProductId = 3,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 10,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 240m,
                            ProductId = 4,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 11,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 260m,
                            ProductId = 4,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 12,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 235m,
                            ProductId = 4,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 13,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 155m,
                            ProductId = 5,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 14,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 165m,
                            ProductId = 5,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 15,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 150m,
                            ProductId = 5,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 16,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 3700m,
                            ProductId = 6,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 17,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 3900m,
                            ProductId = 6,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 18,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 3600m,
                            ProductId = 6,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 19,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 105m,
                            ProductId = 7,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 20,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 115m,
                            ProductId = 7,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 21,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 100m,
                            ProductId = 7,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 22,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 580m,
                            ProductId = 8,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 23,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 620m,
                            ProductId = 8,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 24,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 570m,
                            ProductId = 8,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 25,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 140m,
                            ProductId = 9,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 26,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 150m,
                            ProductId = 9,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 27,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 135m,
                            ProductId = 9,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 28,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorA",
                            Price = 110m,
                            ProductId = 10,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 29,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorB",
                            Price = 120m,
                            ProductId = 10,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 30,
                            LastChecked = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "CompetitorC",
                            Price = 105m,
                            ProductId = 10,
                            StockQuantity = 150
                        });
                });

            modelBuilder.Entity("PriceGenius.API.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NewPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("PriceGenius.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPrice = 80m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 120m,
                            MaxPrice = 200m,
                            MinPrice = 95m,
                            Name = "Wireless Mouse",
                            SKU = "WM-001",
                            SellerId = 1,
                            StockQuantity = 150,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CostPrice = 200m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 350m,
                            MaxPrice = 500m,
                            MinPrice = 240m,
                            Name = "Mechanical Keyboard",
                            SKU = "MK-002",
                            SellerId = 1,
                            StockQuantity = 75,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CostPrice = 120m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 180m,
                            MaxPrice = 300m,
                            MinPrice = 145m,
                            Name = "USB-C Hub",
                            SKU = "UH-003",
                            SellerId = 1,
                            StockQuantity = 200,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CostPrice = 150m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 250m,
                            MaxPrice = 400m,
                            MinPrice = 180m,
                            Name = "Webcam HD 1080p",
                            SKU = "WC-004",
                            SellerId = 1,
                            StockQuantity = 90,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CostPrice = 100m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 160m,
                            MaxPrice = 250m,
                            MinPrice = 120m,
                            Name = "Bluetooth Headset",
                            SKU = "BH-005",
                            SellerId = 1,
                            StockQuantity = 300,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CostPrice = 2500m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 3800m,
                            MaxPrice = 5500m,
                            MinPrice = 3000m,
                            Name = "Gaming Monitor 27\"",
                            SKU = "GM-006",
                            SellerId = 2,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CostPrice = 60m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 110m,
                            MaxPrice = 180m,
                            MinPrice = 75m,
                            Name = "Laptop Stand",
                            SKU = "LS-007",
                            SellerId = 2,
                            StockQuantity = 500,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CostPrice = 400m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 600m,
                            MaxPrice = 900m,
                            MinPrice = 480m,
                            Name = "External SSD 1TB",
                            SKU = "ES-008",
                            SellerId = 2,
                            StockQuantity = 120,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CostPrice = 90m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 145m,
                            MaxPrice = 220m,
                            MinPrice = 110m,
                            Name = "Smart Power Strip",
                            SKU = "SP-009",
                            SellerId = 2,
                            StockQuantity = 250,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CostPrice = 70m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 115m,
                            MaxPrice = 180m,
                            MinPrice = 85m,
                            Name = "Wireless Charger",
                            SKU = "WCH-010",
                            SellerId = 2,
                            StockQuantity = 400,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PriceGenius.API.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinProfitMargin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@techstore.com",
                            IsActive = true,
                            MinProfitMargin = 15m,
                            Name = "TechStore"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sales@gadgetworld.com",
                            IsActive = true,
                            MinProfitMargin = 20m,
                            Name = "GadgetWorld"
                        });
                });

            modelBuilder.Entity("PriceGenius.API.Models.AgentDecision", b =>
                {
                    b.HasOne("PriceGenius.API.Models.Product", "Product")
                        .WithMany("AgentDecisions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceGenius.API.Models.Competitor", b =>
                {
                    b.HasOne("PriceGenius.API.Models.Product", "Product")
                        .WithMany("Competitors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceGenius.API.Models.PriceHistory", b =>
                {
                    b.HasOne("PriceGenius.API.Models.Product", "Product")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceGenius.API.Models.Product", b =>
                {
                    b.HasOne("PriceGenius.API.Models.Seller", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("PriceGenius.API.Models.Product", b =>
                {
                    b.Navigation("AgentDecisions");

                    b.Navigation("Competitors");

                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("PriceGenius.API.Models.Seller", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
